---
jobs:
- name: build-bosh-agent
  plan:
  - aggregate:
    - get: src-stemcell
      trigger: true
    - get: src-bosh-agent
      trigger: true
  - task: build-bosh-agent
    file: src-stemcell/ci/tasks/build-bosh-agent/build-bosh-agent.yml

resources:
- name: src-stemcell
  type: git
  source:
    uri: https://github.com/daniellavoie/scaleway-ubuntu-trusty-stemcell
    branch: master
- name: src-bosh-agent
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-agent
    branch: master