---
jobs:
- name: build-scaleway-ubuntu-trusty-stemcell
  plan:
  - aggregate:
    - get: version
    - get: src-stemcell
      trigger: true
    - get: src-bosh-agent
      trigger: true
  - task: build-stemcell
    file: src-stemcell/ci/tasks/build-stemcell/build-stemcell.yml
  - put: artifact-stemcell
    params:
      file: "artifact-stemcell/scaleway-ubuntu-trusty-stemcell.tgz"
      acl: public-read

resources:
- name: version
  type: semver
  source:
    driver: git
    uri: {{github-lock-url}}
    branch: locks
    file: current-version
    initial_version: 0.0.1
- name: src-stemcell
  type: git
  source:
    uri: https://github.com/daniellavoie/scaleway-ubuntu-trusty-stemcell
    branch: master
- name: src-bosh-agent
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-agent
    branch: master
- name: artifact-stemcell
  type: s3
  source:
    bucket: scaleway-ubunty-trusty-stemcell
    region_name: ca-central-1
    access_key_id: {{s3-artifact-key-id}}
    secret_access_key: {{s3-artifact-secret}}
    versioned_file: scaleway-ubuntu-trusty-stemcell.tgz