---
jobs:
- name: build-bosh-agent
  plan:
  - aggregate:
    - get: src-stemcell
      trigger: true
    - get: src-bosh-agent
      trigger: true
  - task: build-bosh-agent
    file: src-stemcell/ci/tasks/build-bosh-agent/build-bosh-agent.yml
  - put: artifact-stemcell
    params:
      file: artifact-stemcell/scaleway-ubuntu-trusty-stemcell.tgz
      acl: public-read

resources:
- name: src-stemcell
  type: git
  source:
    uri: https://github.com/daniellavoie/scaleway-ubuntu-trusty-stemcell
    branch: master
- name: src-bosh-agent
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-agent
    branch: master
- name: artifact-stemcell
  type: s3
  source:
    bucket: scaleway-ubunty-trusty-stemcell
    region_name: ca-central-1
    regexp: *
    access_key_id: {{s3-artifact-key-id}}
    secret_access_key: {{s3-artifact-secret}}